config/routes.rb
Rails.application.routes.draw do

  resources :products do
     collection do
       get 'autocomplete_name'
       get 'lookup'
       get 'search'
     end
   end
  resources :product_rels

  devise_for :users

  get "/about" => "home#about"

  root to: "home#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  has_many :parent_product_rels, dependent: :destroy, foreign_key: :child_id, class_name: "ProductRel"
  has_many :parents, through: :parent_product_rels, source: :parent

  has_many :child_product_rels, dependent: :destroy, foreign_key: :parent_id, class_name: "ProductRel"
  has_many :children, through: :child_product_rels, source: :child

  has_many :product_impact_line_items, dependent: :destroy
  has_many :impact_line_items, through: :product_impact_line_items

  validates :name, presence: true, uniqueness: true

  mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode

  def self.search(search_term)
    where(["name ILIKE :term OR description ILIKE :term", {term: "%#{search_term}%"} ])
  end

  def find_product_impact_line_item(impact_line_item)
    product_impact_line_items.find_by_impact_line_item_id(impact_line_item.id)
  end

  # def impact_entries
  #   ImpactEntry.find(:all,
  #              :joins=>" JOIN stores ON Categories.manager_id = managers.id
  #                        JOIN regions ON stores.region_id = regions.id
  #                        JOIN readings ON readings.region_number = regions.number"
  #              :conditions=>"manager.name = 'John Smith' AND regions.number = '1234567'"
  #              :limit=>100)
  # end

  def child_quantity(child)
    child_product_rels.find_by_child_id(child).child_quantity
  end

  # return true if any child product address is present so we can display the map
  def child_product_addresses_present?
    children.each do |child|
      if child.address.present?
        return true
      end
    end
    false
  end

  def children_with_address
    children.where("address IS NOT null")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :lookup, :autocomplete_name, :search]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    #@products = Product.all
    @products = Product.order('created_at ASC').page(params[:page]).per(12)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    #@product_impact_line_items = @product.product_impact_line_items.includes(:impact_line_item, :impact_entries)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  def lookup
    barcode = params[:barcode]
    barcode_type = params[:barcode_type]
    scanned_product = Product.where(barcode_type: barcode_type, barcode: barcode).first
    respond_to do |format|
      format.json { render json: scanned_product, serializer: ProductLookupSerializer }
    end
  end

  def search
    @products = Product.search(params[:search]).page(params[:page]).per(12)
    render :index
  end

  def autocomplete_name
    @products = Product.order(:name).where("name ILIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      #byebug
      format.html
      format.json {
        render json: @products.map{|p| {label: p.name, value: p.id} }.to_json
      }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    #byebug
    params.require(:product).permit(:name, :parent_product_id, :user_id)
    @product = Product.new(product_params)

    # set up associations
    @product.user = current_user

    ActiveRecord::Base.transaction do

      respond_to do |format|
        if @product.save

          ImpactLineItem.all.each do |impact_line_item|
              product_impact_line_item = @product.product_impact_line_items.create(product_id: @product.id, impact_line_item_id: impact_line_item.id)

              Category.all.each do |category|
                # byebug
                # in form.html.erb, impact_entry has the following HTML impact_entry[<%=impact_line_item.id%>][<%=category.id%>]
                ImpactEntry.create( product_impact_line_item_id: product_impact_line_item.id,
                                    category_id: category.id,
                                    value: params[:impact_entry][impact_line_item.id.to_s][category.id.to_s])
              end

          end

          format.html { redirect_to @product, notice: 'Product was successfully created.' }
          format.json { render json: @product, status: :created }
        else
          format.html { render action: 'new' }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end

    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update

    ActiveRecord::Base.transaction do
      respond_to do |format|
        if @product.update(product_params)

          ImpactLineItem.all.each do |impact_line_item|
            product_impact_line_item = @product.product_impact_line_items.find_by_impact_line_item_id(impact_line_item.id)

            Category.all.each do |category|
                impact_entry = product_impact_line_item.find_impact_entry(category)
                impact_entry.update( value: params[:impact_entry][impact_line_item.id.to_s][category.id.to_s])
            end
          end

          format.html { redirect_to @product, notice: 'Product was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      #@product = Product.find params[:id]
      @product = Product.where(id: params[:id]).includes(
        {product_impact_line_items: [:impact_line_item, :impact_entries]}).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :barcode_type, :barcode, :image, :address, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def products_json(products_json)
    #byebug
    Gmaps4rails.build_markers(products_json) do |product, marker|
      marker.lat product.latitude
      marker.lng product.longitude
      marker.infowindow product.name
      # marker.picture({
      #   url:   image_path('yellow_MarkerS.png'),
      #   width: "20",
      #   height: "32"
      #  })
    end
  end
end

app/views/products/_child_product.html.erb
<%# byebug  %>
<tr id="<%= dom_id(child_product) %>" style="<%= style if defined?(style) %>">
   <td class="col-sm-2"><%= child_product.id %></td>
   <td class="col-sm-2"><%= child_product.name %></td>
   <td class="col-sm-2"><%= parent_product.child_quantity(child_product) %></td>
   <td class="col-sm-2"><%= link_to 'Show', child_product %></td>
   <td class="col-sm-2"><%= link_to 'Edit', edit_product_path(child_product) %></td>
   <td class="col-sm-2">  <%= link_to "Remove",
                            product_rel_path(ProductRel.find_by_parent_child(parent_product, child_product)),
                            data: {confirm: "Are you sure you want to remove this source product?"},
                            method: :delete, remote: true %>
                          </td>

</tr>

app/views/products/_child_product_form.html.erb
<%= form_tag product_rels_path, html: {class: "form-horizontal"}, remote: true do |f| %>

   <div class="form-group">
      <%#= label_tag :parent_id, "Parent", html: {class: "col-md-2 control-label"} %>
      <%#= text_field_tag :parent_id %>
      <%= hidden_field_tag "parent_id", parent_product.id %>
      <div class="form-group col-xs-3 col-md-3">
        <%= label_tag :child_id, "Source Product Id", html: {class: "col-md-2 control-label"} %>
        <%= text_field_tag :child_id, nil, placeholder: 'Enter product ID' %>
      </div>

      <div class="form-group col-xs-3 col-md-3">
        <%= label_tag :child_product_name_search, "Source Product Name", html: {class: "col-md-2 control-label"} %>
        <%= text_field_tag :child_product_name_search, nil, placeholder: 'Enter search term ...' %>
      </div>

      <div class="form-group col-xs-3 col-md-3">
        <%= label_tag :child_quantity, "Source Quantity", html: {class: "col-md-2 control-label"} %>
        <%= text_field_tag :child_quantity, 1 %>
      </div>

      <div class="form-group col-xs-3 col-md-3">
        <%#= submit_tag "Add Source Product", 	data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
        <label id="source-product-submit-label" for="source-product-submit" class="btn"><i class="glyphicon glyphicon-plus"></i>Add</label>
        <input id="source-product-submit" type="submit" value="Go" class="hidden" />
      </div>
  </div>


  <div class="form-group">

  </div>
<% end %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%#= f.input :image %>

    <div class="control-group">
      <div class="attach-set">
        <%= f.input :image, input_html: { class:'hidden-input' }, label: 'Upload Image' %>
        <div class="input-append">
          <input id="file-display" class="input-large uneditable-input" type="text">
          <a id="upload-btn" class="btn btn-primary"><i class="icon-upload-alt"></i> Browse</a>
        </div>
      </div> <!-- /attach-set -->
    </div> <!-- /control-group -->

    <%= f.input :barcode_type, label: "Barcode Type" %>
    <%= f.input :barcode %>
    <%= f.input :address %>
    <%= f.input :contact_email, label: "Contact E-mail" %>
    <%= f.input :details_url, label: "Link to Details" %>
    <%#= f.association :user %>

    <table class="table table-medium">
      <thead>
        <tr>
          <th class="col-md-2"></th>
          <% Category.all.each do |category| %>
              <th class="col-md-2"><%= category.name %></th>
          <% end %>
        </tr>

      </thead>

      <tbody>

        <% ImpactLineItem.all.each do |impact_line_item| %>
            <tr>
               <td><%= impact_line_item.name %></td>
               <% Category.all.each do |category| %>
                  <%# byebug %>
                  <% if @product.persisted? %>
                    <% product_impact_line_item = @product.find_product_impact_line_item(impact_line_item)  %>
                    <td class="col-md-2">
                      <input type="text"
                              name="impact_entry[<%=impact_line_item.id%>][<%=category.id%>]"
                              value="<%= product_impact_line_item.find_impact_entry(category).value %>"
                              <%#= impact_line_item.name == "Total Impact" ? "disabled" : "" %> />
                    </td>
                  <% else %>
                    <td class="col-md-2"><input type="text" name="impact_entry[<%=impact_line_item.id%>][<%=category.id%>]"/></td>
                  <% end %>
               <% end %>
            </tr>
       <% end %>
     </tbody>


    </table>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>
<%#= react_component "ProductImpactTable", {product: ProductSerializer.new(@product).serializable_hash} %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products Listing</h1>

<%= paginate(@products) %>
<div class="pagination_info">
  <%= page_entries_info @products %>
</div>

<div class="row products">
  <% @products.each do |product| %>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 product-index-image-container-with-name">
    <% if product.image.present? %>
      <div class="product-index-image-container">
        <%= link_to image_tag(product.image.url(:thumb), class: "product-index-image"),
            product_path(product) %>
      </div>
      <span><%= link_to product.name, product_path(product) %></span>
    <% else %>
      <%= link_to(product, class: "product-index-placeholder-link") do %>
        <div class="product-index-image-container">
            <span class="product-index-placeholder-name"> <%= product.name %> </span>
        </div>
      <% end %>
      <span><%= link_to product.name, product_path(product) %></span>
    <% end %>
    </div>
  <% end %>
</div>

<%= paginate(@products) %>


<%#= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
  <!-- <p id="notice"><%#= flash[:notice] %></p>
  <p id="alert"><%#= flash[:alert] %></p> -->

  <div class="col-sm-8">
    <div class="h2"><%= @product.name %></div>
    <hr>
    <p>
      <strong>Product Id:</strong>
      <%= @product.id %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>

    <p>
      <strong>Barcode Type:</strong>
      <%= @product.barcode_type %>
    </p>

    <p>
      <strong>Barcode:</strong>
      <%= @product.barcode %>
    </p>

    <p>
      <strong>Manufactured Address:</strong>
      <%= @product.address %>
    </p>

    <p>
      <strong>Contact E-mail:</strong>
      <%= @product.contact_email %>
    </p>

    <p>
      <strong>Link to Details:</strong>
      <%= link_to @product.details_url, @product.details_url %>
    </p>
  </div>

  <div class="col-sm-4">
    <% if @product.image.present? %>
      <%= image_tag @product.image.url(:small), class: "product-image" %>
    <% end %>
  </div>

</div>

<div style = "overflow-x:auto">
  <table id="impacts-table" class="table table-bordered table-medium">
    <thead>
      <tr>
        <th class="col-sm-2 headcol"></th>
        <% Category.all.each do |category| %>
            <th class="col-sm-2"><%= category.name %></th>
        <% end %>
      </tr>

    </thead>

    <tbody>
      <% product_impact_line_items = @product.product_impact_line_items %>
      <%# product_impact_line_items.all.each do |product_impact_line_item| %>
      <%# specify relationship to be included in the result sult %>
      <% product_impact_line_items.each do |product_impact_line_item| %>
          <tr>
            <th class="headcol" scope="row"><%= product_impact_line_item.impact_line_item.name %></th>
             <% Category.all.each do |category| %>
                 <%# byebug %>
                <td class="col-sm-2"> <%= product_impact_line_item.find_impact_entry(category).value %></td>
             <% end %>
          </tr>

      <% end %>

   </tbody>
  </table>
</div>

<div class="row">
  <div class="col-sm-6">
    <%= link_to 'Edit Product', edit_product_path(@product), class: "btn btn-primary" %>
    <%= link_to 'Back', products_path, class: "btn btn-primary" %>
  </div>

  <div class="col-sm-6">
    <a href="#source-products-section" class="btn btn-circle page-scroll pulse">
      <i class="fa fa-angle-double-down"></i> </a>
  </div>
</div>

<section id="source-products-section" class="container content-section">
  <h3 id="source-products-header">Source Products</h3>

  <div id="child-product-form">
    <%= render "/products/child_product_form", parent_product: @product %>
  </div>

  <hr>

  <table class="table table-medium" id="child-products">
    <thead>
        <tr>
          <th class="col-sm-2">Product Id</th>
          <th class="col-sm-2">Name</th>
          <th class="col-sm-2">Quantity</th>
          <th class="col-sm-2"></th>
          <th class="col-sm-2"></th>
          <th class="col-sm-2"></th>
        </tr>
      </div>
    </thead>

    <tbody>
      <div>
        <% @product.children.each do |child_product| %>
          <%= render partial: "/products/child_product", locals: {parent_product: @product, child_product: child_product} %>
        <% end %>
      </div>
   </tbody>
  </table>

  <h3>Product and Source Products Locations</h3>
  <%# byebug %>
  <% if @product.address.present? || @product.child_product_addresses_present? %>
  <div>
    <div id="map" style='height: 600px;'></div>
  </div>

  <%# byebug %>
  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: { scrollwheel: false, zoomControl: true }, internal: {id: 'map'}}, function(){

      var marker_product = [];
      var markers_source_products = [];
      <% if @product.address.present? %>
        marker_product = handler.addMarkers([
          {
            "lat": <%= @product.latitude %>,
            "lng": <%= @product.longitude %>,
            "picture": {
              //"url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
              "url": "<%= asset_path('red_MarkerP.png') %>",
              "width":  20,
              "height": 32
            },
            "infowindow": "<%= @product.name %>"
          }
        ]);
      <% end %>
      <% if @product.child_product_addresses_present? %>
        markers_source_products = handler.addMarkers(<%= raw products_json(@product.children_with_address).to_json %>);
      <% end %>
      var markers = marker_product.concat(markers_source_products);
      //debugger;
      updateMarkers(handler, markers);

      //// move to updateMarkers in map.js
      // handler.bounds.extendWith(markers);
      // // set the zoom differently for a single marker
      // if (markers.length === 1) {
      //   handler.fitMapToBounds();
      //   handler.getMap().setZoom(17);
      // } else {
      //   handler.fitMapToBounds();
      // }

    });
  </script>
  <% else %>
    <p>No addresses provided for product or source products.</p>
  <% end %>
</section>