config/routes.rb
Rails.application.routes.draw do

  resources :products do
     collection do
       get 'autocomplete_name'
       get 'lookup'
       get 'search'
     end
   end
  resources :product_rels

  devise_for :users

  get "/about" => "home#about"

  root to: "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeFootprints</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" href="#">Brand</a> -->
          <%= image_tag('awesome_footprint_144_144.png', id: "navbar-logo", class: "navbar-brand") %>
          <%= link_to "Awesome Footprints", root_path, class: "navbar-brand"  %>

        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
            <!-- <li><a href="#">Link</a></li> -->
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "New Product", new_product_path %></li>
            <li><%= link_to "All Products", products_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="#"></a></li> -->
            <% if user_signed_in? %>
              <li id="user-dropdown-menu" class="dropdown">
                <a id="user-dropdown-button" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= "Hello #{current_user.first_name}" %><span class="caret"></span></a>
                <ul id="user-dropdown-items" class="dropdown-menu" role="menu">
                  <!-- <li><a href="#">Action</a></li> -->
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>                  <!-- <li class="divider"></li> -->
                  <!-- <li><a href="#">Separated link</a></li> -->
                  <li class="divider"></li>
                  <!-- <li><a href="#">One more separated link</a></li> -->
                  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <!-- <li><a href="#">Sign In</a></li> -->
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li> <%= link_to "Sign Up", new_user_registration_path, id: "btn-sign-up" %></li>
            <% end %>
          </ul>
          <!-- <div class="navbar-right navbar-space" style="width:200px; background-color:red">a</div> -->
          <!-- <form class="navbar-form navbar-right" role="search" action="posts/search" method="GET"> -->
          <form class="navbar-form navbar-right" role="search" action=<%="#{search_products_path}"%> method="GET">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search" name="search">
            </div>
            <button id="btn-navbar-search" type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% elsif flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <!-- <% if flash[:notice] %>
      <div id="notice" class="notice notice-success">
        <%#= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div id="alert" class="alert alert-danger">
        <%#= flash[:alert] %>
      </div>
    <% end %>
     -->
    <%= yield %>
  </div>
</body>
</html>